### ISSUE TITLE
invalid variables

### ISSUE THREAD

**Issue by hafwan** [HakamRaza/Malaysia-MyKad-Reader-Webserver#1]
Good day. This is Hafiz. I have forked and ran the code, but there was an error of variable not available for `dataline `and `datalines[]` in the `utils/mykid.js` code. The system showed error;

```
ReferenceError: dataline is not defined
    at convertMyKidData (C:\xampp\htdocs\Malaysia-MyKad-Reader-Webserver\utils\mykid.js:83:39)
    at C:\xampp\htdocs\Malaysia-MyKad-Reader-Webserver\utils\mykid.js:48:32
    at ChildProcess.exithandler (node:child_process:414:7)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

```
I have since updated the code to use the variables `infoStr `and `rowsStr[]` just like mykad.js. Just wanna let you know about it, in case you have already fixed it please ignore this issue.

**Comment by HakamRaza** [comment]
Hi @hafwan, actually I never tested this for mykid as I don't have any sample card when I developed this. Would be great if you can make a PR for this. Thank you. 😁

**Comment by hafwan** [comment]
Hi uh sorry for the late reply. I missed the notification. I'm gonna go ahead and fix the code after I create a PR
